### ISSUE TITLE
Inject subgens as symlinks instead of hard-copies

### ISSUE THREAD

**Issue by sthzg** [sthzg/generator-subgenext#20]
Symlinking (through `fs.symlinkSync()` and `fs.unlinkSync()` brings two relevant advantages.
- working w/ symlinks _reduces_ `subgenext:deactivate` to an unlink operation, which, even in a worst case w/ an existing bug **and** the user confirming a safety prompt, would not destroy anything serious.
- when authoring extgens, changes in the linked source packages reflect instantly in generators that make use of the linked subgen

**Comment by stylesuxx** [comment]
I was thinking about this yesterday - does this work cross platform, ie. on windows?

**Comment by sthzg** [comment]
Yes, I've checked [the docs](https://nodejs.org/api/fs.html#fs_fs_symlink_target_path_type_callback) and they mention the third argument `type` is only supported on Windows, so I assume it's cross-platform.
