### ISSUE TITLE
Refactor configuration into .yo-rc.json

### ISSUE THREAD

**Issue by sthzg** [sthzg/generator-subgenext#26]
It seems that `.yo-rc.json` is commonly used to store generator configuration (`react-webpack` e.g. does it to store some metadata and which version to use). I propose adopting this, as it seems perfectly integrated into the yo environment and we don't pollute the directory with an additional config file.

@stylesuxx what's your take?

**Comment by stylesuxx** [comment]
Yep - good idea.
